const V="ZI10";
const T={Milan:["MIL","milan"],Roma:["ROM","roma"],Arsenal:["ARS","arsenal"],Chelsea:["CHE","chelsea"],Barcelona:["BAR","barcelona"],Sevilla:["SEV","sevilla"],Bayern:["BAY","bayern"],Leverkusen:["LEV","leverkusen"],PSG:["PSG","psg"],Lyon:["LYO","lyon"]};
const M=[
{id:"mr",l:"Serie A",t:"18:00",h:"Milan",a:"Roma",p:[74,5,21],g:["GOL",68],ou:["OVER 2.5",61],cv:"ALTA CONVERGENZA",ed:"+15%",cf:75,form:["↗ 78%","→ 61%"],opp:[72,68]},
{id:"ac",l:"Premier League",t:"18:30",h:"Arsenal",a:"Chelsea",p:[61,22,17],g:["GOL",63],ou:["OVER 2.5",58],cv:"ALTA CONVERGENZA",ed:"+10%",cf:71,form:["↗ 74%","→ 69%"],opp:[76,74]},
{id:"bs",l:"La Liga",t:"20:00",h:"Barcelona",a:"Sevilla",p:[68,18,14],g:["GOL",72],ou:["OVER 2.5",66],cv:"ALTA CONVERGENZA",ed:"+8%",cf:78,form:["↗ 82%","↘ 57%"],opp:[70,66]},
{id:"bl",l:"Bundesliga",t:"20:30",h:"Bayern",a:"Leverkusen",p:[55,24,21],g:["GOL",69],ou:["OVER 2.5",64],cv:"BUONA CONVERGENZA",ed:"+5%",cf:67,form:["→ 70%","↗ 72%"],opp:[82,80]},
{id:"pl",l:"Ligue 1",t:"21:00",h:"PSG",a:"Lyon",p:[72,16,12],g:["GOL",70],ou:["OVER 2.5",62],cv:"ALTA CONVERGENZA",ed:"+11%",cf:73,form:["↗ 80%","↘ 63%"],opp:[69,64]}
];
const C={
mr:{r:[["xG","1.84","1.21"],["xGA","0.94","1.37"],["xThreat ultimo terzo","1.42","0.96"],["Entrate in area","18","11"],["Tiri in porta","6","4"],["xG / tiro","0.13","0.10"],["Possesso","58%","42%"],["Media Corner","6.0","4.0"]],c:[["Pressione alta","77%","61%"],["Recupero palla","8.7s","11.4s"],["Recuperi offensivi","23%","17%"],["PPDA","8.2","11.7"]],why:[["xG","1.84","1.21","Produzione di occasioni attese superiore."],["xGA","0.94","1.37","Qualità delle occasioni concesse più bassa."],["FORMA","↗ 78%","→ 61%","Ultime 5 gare confrontate con il rendimento precedente e pesate per qualità e recenza."],["ULTIMO TERZO","78","61","Capacità di trasformare il possesso avanzato in minaccia reale."],["QUALITÀ OCCASIONI","0.13","0.10","La pericolosità media evita di premiare semplicemente il numero di tiri."]]},
ac:{r:[["xG","1.71","1.36"],["xGA","1.02","1.28"],["xThreat ultimo terzo","1.31","1.12"],["Entrate in area","16","14"],["Tiri in porta","5","4"],["xG / tiro","0.12","0.11"],["Possesso","54%","46%"],["Media Corner","5.4","4.8"]],c:[["Pressione alta","72%","64%"],["Recupero palla","9.1s","10.3s"],["Recuperi offensivi","21%","18%"],["PPDA","9.0","10.8"]]},
bs:{r:[["xG","2.02","1.03"],["xGA","0.91","1.46"],["xThreat ultimo terzo","1.68","0.91"],["Entrate in area","22","10"],["Tiri in porta","7","3"],["xG / tiro","0.15","0.09"],["Possesso","61%","39%"],["Media Corner","6.2","3.7"]],c:[["Pressione alta","81%","52%"],["Recupero palla","7.9s","12.0s"],["Recuperi offensivi","29%","14%"],["PPDA","7.6","13.2"]]},
bl:{r:[["xG","1.68","1.59"],["xGA","1.12","1.18"],["xThreat ultimo terzo","1.48","1.41"],["Entrate in area","17","16"],["Tiri in porta","6","5"],["xG / tiro","0.14","0.13"],["Possesso","57%","43%"],["Media Corner","5.8","5.1"]],c:[["Pressione alta","74%","71%"],["Recupero palla","8.9s","9.4s"],["Recuperi offensivi","25%","23%"],["PPDA","8.7","9.1"]]},
pl:{r:[["xG","1.96","1.08"],["xGA","0.88","1.41"],["xThreat ultimo terzo","1.61","0.98"],["Entrate in area","20","12"],["Tiri in porta","7","4"],["xG / tiro","0.14","0.10"],["Possesso","59%","41%"],["Media Corner","6.1","4.1"]],c:[["Pressione alta","79%","59%"],["Recupero palla","8.2s","11.2s"],["Recuperi offensivi","27%","16%"],["PPDA","8.0","12.0"]]}
};
const info=(title,text)=>`<button class="info" data-info="${encodeURIComponent(text)}" aria-label="${title} info">i</button>`;
const badge=n=>{let x=T[n];return `<div class="crest ${x[1]}"><span>${x[0]}</span></div>`};
const nav=(id,ic,tx,a)=>`<button class="nav ${a===id?"on":""}" data-nav="${id}"><b>${ic}</b><span>${tx}</span></button>`;
function shell(a){return `<header><div class="brand">SPACE16154<small>FOOTBALL INTELLIGENCE</small></div><div class="engine"><i></i></div></header><main id="main"></main><nav>${nav("dashboard","⌂","Dashboard",a)}${nav("matches","□","Matches",a)}${nav("analysis","◇","Analysis",a)}${nav("teams","♙","Squadre",a)}${nav("more","•••","Altro",a)}</nav>`}
function card(m){return `<button class="fixture" data-detail="${m.id}"><span>${m.t}</span><div>${badge(m.h)}${m.h}</div><em>VS</em><div>${m.a}${badge(m.a)}</div><small>${m.l}</small><b>›</b></button>`}
function stat(t,v,s,ic,r){return `<button class="stat" data-nav="${r}"><small>${t}<b>${ic}</b></small><strong>${v}</strong><span>${s}</span></button>`}
function dashboard(){let m=M[0];main.innerHTML=`<div class="page"><div class="eyebrow">PANORAMICA</div><h1>DASHBOARD</h1><p>Il quadro sintetico prima del dettaglio.</p><div class="stats">${stat("PARTITE OGGI","18","Vai a Matches","□","matches")}${stat("SEGNALI","7","Opportunità","◎","analysis")}${stat("CONFIDENCE MEDIA","71%","Coerenza","◉","analysis")}${stat("DATA QUALITY","96%","Copertura dati","✓","analysis")}</div>
<section class="panel"><div class="head"><h2>☆ MATCH IN EVIDENZA</h2><span>${m.l}</span></div><button class="hero" data-detail="${m.id}"><div>${badge(m.h)}<b>${m.h}</b></div><section><strong>${m.t}</strong><small>OGGI</small><em>VS</em></section><div>${badge(m.a)}<b>${m.a}</b></div></button><div class="preds"><article><small>1X2</small><b>1</b><strong>${m.p[0]}%</strong></article><article><small>GOL / NO GOL</small><b>GOL</b><strong>${m.g[1]}%</strong></article><article><small>OVER / UNDER 2.5</small><b>${m.ou[0]}</b><strong>${m.ou[1]}%</strong></article></div><button class="primary" data-detail="${m.id}">VAI ALL'ANALISI COMPLETA ›</button></section>
<section class="panel"><div class="head"><h2>PROSSIME PARTITE</h2><button class="gold" data-nav="matches">VEDI TUTTE ›</button></div>${M.slice(1).map(card).join("")}</section>
<section class="panel"><div class="head"><h2>◎ TOP SIGNALS</h2><button class="gold" data-nav="analysis">INTELLIGENCE ›</button></div><div class="signals">${M.slice(0,3).map(x=>`<button class="signal" data-detail="${x.id}"><small>${x.cv} ${info("Segnale",x.cv==="ALTA CONVERGENZA"?"Più famiglie di indicatori indipendenti puntano nella stessa direzione.":"La convergenza è buona ma il margine è più sottile.")}</small><b>${x.h} vs ${x.a}</b><span>${x.ed} · Confidence ${x.cf}%</span></button>`).join("")}</div></section></div>`;bind()}
function matches(){main.innerHTML=`<div class="page"><div class="eyebrow">CALENDARIO</div><h1>MATCHES</h1><p>Scegli la lega e poi entra nel dettaglio.</p><div class="leagues">${["Serie A","Premier League","La Liga","Bundesliga","Ligue 1"].map((x,i)=>`<button class="${i?"":"sel"}" data-league="${x}"><span>${x}</span><b>${M.filter(m=>m.l===x).length||2}</b>›</button>`).join("")}</div><section class="panel"><div class="head"><h2>PARTITE DEL GIORNO</h2><span>5 disponibili</span></div><div id="rows">${M.map(card).join("")}</div></section></div>`;bind();document.querySelectorAll("[data-league]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".leagues button").forEach(x=>x.classList.remove("sel"));b.classList.add("sel");let z=M.filter(m=>m.l===b.dataset.league);rows.innerHTML=(z.length?z:M).map(card).join("");bindDetail()})}
function analysis(){let x=[...M].sort((a,b)=>b.cf-a.cf);main.innerHTML=`<div class="page"><div class="eyebrow">INTELLIGENCE</div><h1>ANALYSIS</h1><p>Interpretazione trasversale dei dati, senza duplicare il dettaglio delle partite.</p><section class="panel"><div class="head"><h2>SEGNALI DELLA GIORNATA</h2><span>5 match</span></div>${x.map((m,i)=>`<button class="insight" data-detail="${m.id}"><i>0${i+1}</i><div><b>${m.h} — ${m.a}</b><small>${m.l} · ${m.cv}</small></div><strong>${m.cf}%</strong>›</button>`).join("")}</section><section class="panel"><div class="head"><h2>LETTURE TRASVERSALI</h2><span>MODELLO</span></div><div class="grid4"><article><small>MINACCIA ULTIMO TERZO</small><b>Barcelona</b><strong>84 / 100</strong><p>Capacità di trasformare il possesso avanzato in pericolo.</p></article><article><small>FORMA IN CRESCITA</small><b>Barcelona</b><strong>↗ 82%</strong><p>Direzione positiva nelle ultime 5.</p></article><article><small>PRESSIONE AVANZATA</small><b>Barcelona</b><strong>81%</strong><p>Quota media dei recuperi nell'ultimo terzo.</p></article><article><small>RECUPERO PIÙ RAPIDO</small><b>Barcelona</b><strong>7.9s</strong><p>Tempo corretto per la forza dell'avversario.</p></article></div></section><section class="panel"><div class="head"><h2>PROBABILITY / CONFIDENCE</h2>${info("Probability e Confidence","Probability = quanto il modello pensa sia probabile un esito. Confidence = quanto i diversi blocchi di dati sono coerenti tra loro.")}</div><div class="explain"><b>Probability</b><p>Quanto è probabile un risultato secondo il modello.</p><b>Confidence</b><p>Quanto i dati raccontano una storia coerente.</p><b>Edge</b><p>Potenziale scostamento tra stima del modello e quota disponibile.</p></div></section></div>`;bind()}
function row(a,b,c,t,i=false){return `<div class="row"><span>${a}${i?info(a,t):""}</span><b>${b}</b><b>${c}</b></div>`}
function detail(id){let m=M.find(x=>x.id===id)||M[0],d=C[id];let why=d?.why||[["xG","1.71","1.36","Produzione attesa superiore."],["xGA","1.02","1.28","Concede occasioni meno pericolose."],["FORMA",m.form[0],m.form[1],"Ultime 5 confrontate con il rendimento precedente."],["ULTIMO TERZO","73","66","Minaccia avanzata superiore."],["QUALITÀ OCCASIONI","0.12","0.11","Qualità media delle conclusioni."]];main.innerHTML=`<div class="page"><button class="back" data-nav="matches">‹ MATCHES</button><section class="panel matchdetail"><small>${m.l} · ${m.t} · OGGI</small><div><article>${badge(m.h)}<b>${m.h}</b></article><em>VS</em><article>${badge(m.a)}<b>${m.a}</b></article></div></section>
<section class="panel"><div class="head"><h2>MODELLO ${info("Modello","Combina probabilità, qualità delle occasioni, forma, minaccia nell'ultimo terzo, forza dell'avversario e fattore campo.")}</h2><span class="badges"><i>${m.cv}</i><i>EDGE ${m.ed}</i></span></div><div class="probs"><article><small>1</small><b>${m.p[0]}%</b><span>${m.h}</span></article><article><small>X</small><b>${m.p[1]}%</b><span>Pareggio</span></article><article><small>2</small><b>${m.p[2]}%</b><span>${m.a}</span></article></div><div class="subpred"><span>GOL / NO GOL <b>${m.g[0]} ${m.g[1]}%</b></span><span>OVER / UNDER <b>${m.ou[0]} ${m.ou[1]}%</b></span></div><div class="confidence"><span>CONFIDENCE ${info("Confidence","Non è una seconda probabilità: misura quanto i principali blocchi analitici sono coerenti.")}<b>${m.cf}%</b></span><i style="width:${m.cf}%"></i><small>Coerenza dei dati che portano alla lettura.</small></div><div class="why"><h3>PERCHÉ IL MODELLO VEDE ${m.h.toUpperCase()}?</h3>${why.map(x=>`<article><small>${x[0]}</small><div><b>${x[1]}</b><b>${x[2]}</b></div><p>${x[3]}</p></article>`).join("")}</div><div class="signalbox"><small>LETTURA DEL SEGNALE</small><b>${m.cv} · EDGE ${m.ed}</b><p>Il segnale combina produzione offensiva, difesa, forma, minaccia nell'ultimo terzo e contesto dell'avversario.</p><div>⚠ Rischio: il risultato resta sensibile alla qualità dei dati e alla forza dell'avversario.</div></div></section>
<section class="panel"><div class="head"><h2>CONFRONTO DATI</h2><span>${m.h} · ${m.a}</span></div><div class="thead"><span>INDICATORE</span><b>${T[m.h][0]}</b><b>${T[m.a][0]}</b></div>${(d?.r||C.mr.r).map(x=>row(...x)).join("")}</section>
<section class="panel"><div class="head"><h2>INDICATORI DI CONTROLLO</h2><span>CONTESTO</span></div>${(d?.c||C.mr.c).map(x=>row(x[0],x[1],x[2],x[0]==="PPDA"?"Passaggi concessi prima della pressione.":"",x[0]==="PPDA")).join("")}<p class="note"><b>Pressione alta</b> = media della quota di recuperi effettuati nell'ultimo terzo. Il dato viene calcolato sul comportamento di recupero, non sul semplice possesso.</p></section>
<section class="panel"><div class="head"><h2>FORMA</h2><span>ULTIME 5 ${info("Forma","Confronta le ultime cinque partite con il rendimento precedente. Tiene conto di risultati, gol fatti e concessi e statistiche offensive e difensive, ma anche della qualità delle occasioni e di come vengono create o concesse: un gol fortunoso da grande distanza non pesa come un'occasione pulita dentro l'area. Le gare più recenti hanno più peso.")}</span></div><div class="forms"><article><b>${m.h}</b><strong>${m.form[0]}</strong><small>Ultime 5</small></article><article><b>${m.a}</b><strong>${m.form[1]}</strong><small>Ultime 5</small></article></div></section>
<section class="panel"><div class="head"><h2>FORZA AVVERSARIO</h2><span>1–100 ${info("Forza avversario","Rating dinamico ottenuto combinando qualità offensiva e difensiva, xG/xGA, minaccia nell'ultimo terzo, rendimento recente e livello degli avversari affrontati.")}</span></div><div class="opps"><article><b>${m.h}</b><strong>${m.opp[0]}</strong><small>Rating dinamico</small></article><article><b>${m.a}</b><strong>${m.opp[1]}</strong><small>Rating dinamico</small></article></div></section>
<section class="panel"><div class="head"><h2>DATI E AFFIDABILITÀ</h2><span class="quality">96%</span></div><div class="qualitylist"><span>Fixture <b>Completo</b></span><span>xG / xGA <b>Completo</b></span><span>Forma <b>Completo</b></span><span>Quote <b>Demo</b></span></div></section></div>`;bind()}
function bindDetail(){document.querySelectorAll("[data-detail]").forEach(x=>x.onclick=()=>detail(x.dataset.detail))}
function bind(){document.querySelectorAll("[data-nav]").forEach(x=>x.onclick=()=>route(x.dataset.nav));bindDetail();document.querySelectorAll(".info").forEach(x=>x.onclick=e=>{e.stopPropagation();modal(decodeURIComponent(x.dataset.info))})}
function modal(t){let o=document.createElement("div");o.className="modal";o.innerHTML=`<div><button>×</button><div class="eyebrow">INFO</div><p>${t}</p></div>`;document.body.appendChild(o);o.querySelector("button").onclick=()=>o.remove();o.onclick=e=>{if(e.target===o)o.remove()}}
function route(n){document.body.innerHTML=shell(n);if(n==="dashboard")dashboard();else if(n==="matches")matches();else if(n==="analysis")analysis();else simple(n==="teams"?"SQUADRE":"ALTRO","Sezione pronta per i prossimi dati.");scrollTo(0,0)}
function simple(t,p){main.innerHTML=`<div class="page empty"><div class="eyebrow">SPACE16154</div><h1>${t}</h1><p>${p}</p></div>`;bind()}
route("dashboard");
if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js?v=10.0.0",{updateViaCache:"none"}).catch(()=>{}));