const D={
f:{league:"Serie A",date:"12 Maggio 2025",time:"20:45",home:"Milan",away:"Roma",hc:"MIL",ac:"ROM",p1:74,px:16,p2:10,under:52,over:48,goal:68,nogoal:32},
games:[["20:45","Milan","Roma","Serie A","MIL","ROM",1,74],["18:00","Juventus","Inter","Serie A","JUV","INT",0,65],["18:00","Lazio","Atalanta","Serie A","LAZ","ATA",0,58],["20:45","Fiorentina","Napoli","Serie A","FIO","NAP",0,61],["17:30","Man City","Arsenal","Premier League","MCI","ARS",0,65],["17:30","Liverpool","Chelsea","Premier League","LIV","CHE",0,62],["21:00","Barcelona","Real Madrid","La Liga","BAR","RMA",0,58],["15:30","Bayern","Dortmund","Bundesliga","BAY","BVB",0,63]],
m:[["⚡","Threat Creation","Capacità di creare occasioni pericolose attraverso qualità e quantità delle azioni offensive.","78","64","+14","g"],["⬡","Defense Stability","Solidità difensiva e prevenzione del pericolo concesso.","74","67","+7","g"],["↗","Forma (pesata avversari)","Forma recente valutata in base alla forza degli avversari affrontati.","82","61","+21","g"],["◎","Opponent Strength","Forza dell'avversario affrontato di recente.","71","76","-5","r"],["♧","Pressing / PPDA","Intensità della pressione e recuperi alti effettuati.","77","62","+15","g"],["♙","Availability (Assenze)","Impatto di assenze e disponibilità della rosa.","91","84","+7","g"]],
tech:[["xG","1.84","1.26"],["xGA","0.94","1.32"],["Ultimo terzo","64.2","50.8"],["Qualità tiro","0.13","0.10"],["PPDA","9.2","12.6"]],
signals:[["High Confidence","Milan - Roma","Esito: 1","74%","9/10","c"],["Value Bet","Juventus - Inter","Doppia chance: X2","62%","7/10","v"],["Forma Modello","Man City - Arsenal","Over 2.5","65%","8/10","f"]],
rank:[["Inter",82,"↗"],["Napoli",80,"↗"],["Milan",79,"↗"],["Juventus",76,"→"],["Atalanta",75,"↗"],["Lazio",72,"↗"],["Roma",68,"→"],["Fiorentina",65,"→"]]
};
const crest=x=>`<span class="crest">${x}</span>`;
const inf=(t,x)=>`<button class="info" data-info="${encodeURIComponent(x)}">i</button>`;
function nav(id,ic,l,a){return `<button class="nav ${a===id?"on":""}" data-nav="${id}"><b>${ic}</b><span>${l}</span></button>`}
function shell(a){return `<header><div class="brand">${crest("⚽")}<div><strong>FOOTBALL16154</strong><small>FOOTBALL INTELLIGENCE</small></div></div><i class="online"></i></header><main id="main"></main><nav>${nav("dashboard","⌂","Dashboard",a)}${nav("matches","□","Matches",a)}${nav("analysis","◇","Analysis",a)}${nav("signals","◎","Top Signals",a)}${nav("more","•••","More",a)}</nav>`}
function probs(f){return `<section class="panel"><h2>PROBABILITÀ DEL MODELLO ${inf("Probabilità","Le percentuali sono generate combinando le sei macroaree del modello e gli indicatori sottostanti.")}</h2><div class="probs"><div><b>1X2</b><p><em>1<strong>${f.p1}%</strong></em><span>X<strong>${f.px}%</strong></span><span>2<strong>${f.p2}%</strong></span></p><small>Risultato più probabile: <i>1 (${f.p1}%)</i></small></div><div><b>UNDER / OVER 2.5</b><p><em>Under 2.5<strong>${f.under}%</strong></em><span>Over 2.5<strong>${f.over}%</strong></span></p><small>Soglia: 2.5 gol</small></div><div><b>GOL / NO GOL</b><p><em>Gol<strong>${f.goal}%</strong></em><span>No Gol<strong>${f.nogoal}%</strong></span></p><small>Probabilità di Gol: <i>Alta</i></small></div></div></section>`}
function model(){return `<section class="panel"><h2>ANALISI DEL MODELLO ${inf("Analisi del modello","Le sei macroaree contribuiscono alla valutazione complessiva del match.")}</h2><div class="score"><div>${crest("MIL")}<b>MILAN</b><strong>79</strong><small>/100</small></div><div><label>MODEL SCORE</label><strong>+11</strong><i>Vantaggio MILAN</i></div><div><strong>68</strong><small>/100</small><b>ROMA</b>${crest("ROM")}</div></div>${D.m.map(x=>`<div class="macro"><div class="mn"><span>${x[0]}</span><div><b>${x[1]} ${inf(x[1],x[2]+" Il valore viene calcolato combinando diversi indicatori sottostanti, pesati dal modello.")}</b><small>${x[2]}</small></div></div><strong class="${x[6]}">${x[3]}</strong><em class="${x[6]}">${x[5]}</em><strong>${x[4]}</strong><button>⌄</button></div>`).join("")}<p class="note">${inf("Valori","I valori delle macroaree vanno da 0 a 100. Più è alto, migliore è la performance dell'area.")} I valori vanno da 0 a 100. Più è alto, migliore è la performance dell'area.</p></section>`}
function accord(title,body){return `<section class="panel acc"><button class="acc-h"><b>${title}</b><span>⌄</span></button><div class="acc-b">${body}</div></section>`}
function detail(){let f=D.f;document.querySelector("#main").innerHTML=`<div class="page detail"><div class="mh"><button data-nav="matches">‹</button><button>☆</button><h1>${f.home} - ${f.away}</h1><p>${f.league} · ${f.date} · ${f.time}</p><div class="teams"><div>${crest(f.hc)}<b>MILAN</b></div><strong>VS</strong><div>${crest(f.ac)}<b>ROMA</b></div></div><span class="pill">☆ Match in evidenza</span></div>${probs(f)}${model()}${accord("▥  DATI TECNICI - CONFRONTO",`<div class="th"><span>INDICATORE</span><b>MILAN</b><b>ROMA</b></div>${D.tech.map(x=>`<div class="tr"><span>${x[0]} ${inf(x[0],"Indicatore tecnico usato dal modello come parte del confronto.")}</span><b>${x[1]}</b><b>${x[2]}</b></div>`).join("")}`)}${accord("♙  ASSENZE PRINCIPALI",`<div class="cols"><div><b>MILAN</b><p>R. Leao (In dubbio) · Thiaw (Out) · Loftus-Cheek (Out)</p></div><div><b>ROMA</b><p>Dybala (In dubbio) · Smalling (Out) · Azmoun (Out)</p></div></div>`)}${accord("▦  INFORMAZIONI PARTITA",`<div class="infos"><div>Stadio<b>San Siro - Milano</b></div><div>Meteo<b>16°C Sereno</b></div><div>Arbitro<b>D. Orsato</b></div><div>Ultimo incontro<b>Milan 3 - 1 Roma<br>(14/01/2025)</b></div></div>`)}${accord("♙  FORMAZIONI / PROBABILI FORMAZIONI",`<div class="cols"><div><b>MILAN</b><strong>4-2-3-1</strong><small>Probabile formazione demo</small></div><div><b>ROMA</b><strong>3-4-2-1</strong><small>Probabile formazione demo</small></div></div>`)}</div>`;bind()}
function fixture(x){return `<button class="fixture" data-open><span><b>${x[0]}</b><small>${x[3]}</small></span><div>${crest(x[4])}<b>${x[1]}</b></div><em>VS</em><div><b>${x[2]}</b>${crest(x[5])}</div><strong>${x[7]}%</strong></button>`}
function sig(x){return `<article class="signal ${x[5]}"><div><small>${x[0]}</small><b>${x[1]}</b><p>${x[2]}</p></div><strong>${x[3]}</strong><em>${x[4]}</em></article>`}
function dashboard(){let f=D.f;document.querySelector("#main").innerHTML=`<div class="page"><span class="eyebrow">PANORAMICA</span><h1>DASHBOARD</h1><p>Analisi e segnali dai match più interessanti.</p><section class="panel"><h2>☆ MATCH IN EVIDENZA <small>Serie A</small></h2><div class="dashteams"><div>${crest("MIL")}<b>MILAN</b></div><strong>VS</strong><div>${crest("ROM")}<b>ROMA</b></div></div><p class="center">${f.date} · ${f.time}</p><div class="dashp"><em>1 <b>${f.p1}%</b></em><span>X <b>${f.px}%</b></span><span>2 <b>${f.p2}%</b></span></div><div class="dashp two"><em>Gol ${f.goal}%</em><span>Under ${f.under}%</span></div><button class="primary" data-open>VAI ALL'ANALISI COMPLETA ›</button></section><section class="panel"><h2>TOP SIGNALS <button data-nav="signals">VEDI TUTTI ›</button></h2>${D.signals.map(sig).join("")}</section><section class="panel"><h2>PROSSIME PARTITE <button data-nav="matches">VEDI TUTTE ›</button></h2>${D.games.slice(1,5).map(fixture).join("")}</section></div>`;bind()}
function matches(){let ls=[...new Set(D.games.map(x=>x[3]))];document.querySelector("#main").innerHTML=`<div class="page"><span class="eyebrow">CALENDARIO</span><h1>MATCHES</h1><p>Scegli una partita e apri il dettaglio.</p><div class="tabs"><button class="on">Oggi</button><button>Domani</button><button>Tutti</button><button>⌕</button></div>${ls.map(l=>`<section><h2 class="league">${l}</h2>${D.games.filter(x=>x[3]===l).map(fixture).join("")}</section>`).join("")}</div>`;bind()}
function analysis(){document.querySelector("#main").innerHTML=`<div class="page"><span class="eyebrow">ANALISI</span><h1>CLASSIFICA</h1><p>Ranking del modello e dettaglio squadra.</p><div class="tabs"><button class="on">Classifica</button><button>Trend</button></div><div class="select">Serie A <span>⌄</span></div><section class="panel ranking">${D.rank.map((r,i)=>`<button><span>${i+1}</span><b>${crest(r[0].slice(0,3).toUpperCase())} ${r[0]}</b><strong>${r[1]}</strong><em>${r[2]}</em></button>`).join("")}</section><section class="panel"><h2>MILAN · DETTAGLIO MODELLO</h2><div class="teamscore">${crest("MIL")}<b>79 / 100</b><span>Trend positivo</span></div>${D.m.map(x=>`<div class="mini"><span>${x[1]}</span><b>${x[3]}</b><i><em style="width:${x[3]}%"></em></i></div>`).join("")}<div class="form"><b>FORMA RECENTE (PESATA AVVERSARI)</b><span>W</span><span>W</span><span>D</span><span>W</span><span>W</span><small>Punteggio medio avversari: 72/100</small></div></section></div>`;bind()}
function signals(){document.querySelector("#main").innerHTML=`<div class="page"><span class="eyebrow">SEGNALI</span><h1>TOP SIGNALS</h1><p>Filtra i segnali per categoria.</p><div class="filters"><button class="on">Tutti</button><button>Confidence</button><button>Value</button><button>Forma Modello</button></div>${D.signals.map(sig).join("")}</div>`;bind()}
function more(){document.querySelector("#main").innerHTML=`<div class="page"><span class="eyebrow">ALTRO</span><h1>MORE</h1><p>Funzioni e dati di controllo.</p><button class="more" data-perf><b>▥</b><span><strong>Model Performance</strong><small>Storico verificabile delle performance.</small></span>›</button><button class="more"><b>◉</b><span><strong>Dati e affidabilità</strong><small>Copertura e stato delle fonti.</small></span>›</button><button class="more"><b>i</b><span><strong>Come leggere i dati</strong><small>Confidence, Value e Forma.</small></span>›</button></div>`;bind()}
function performance(){document.querySelector("#main").innerHTML=`<div class="page"><span class="eyebrow">ALTRO</span><h1>MODEL PERFORMANCE</h1><p>Storico delle performance del modello.</p><section class="panel perf"><div class="filters"><button class="on">Panoramica</button><button>1X2</button><button>Under/Over</button><button>Gol/No Gol</button><button>Confidence</button><button>Value</button></div><div class="kpi"><div>Accuracy<b>67%</b></div><div>Campione demo<b>120</b></div><div>Periodo<b>30 gg</b></div></div><div class="chart"><b>Trend Model Score</b><div><i></i><i></i><i></i><i></i><i></i></div><small>72 · 75 · 74 · 78 · 79</small></div></section></div>`;bind()}
function infoModal(t){let o=document.createElement("div");o.className="modal";o.innerHTML=`<div><button>×</button><p>${t}</p></div>`;document.body.append(o);o.firstChild.firstChild.onclick=()=>o.remove()}
function bind(){document.querySelectorAll("[data-nav]").forEach(x=>x.onclick=()=>route(x.dataset.nav));document.querySelectorAll("[data-open]").forEach(x=>x.onclick=()=>route("detail"));document.querySelectorAll(".info").forEach(x=>x.onclick=e=>{e.stopPropagation();infoModal(decodeURIComponent(x.dataset.info))});document.querySelectorAll(".acc-h").forEach(x=>x.onclick=()=>x.parentNode.classList.toggle("open"));document.querySelectorAll("[data-perf]").forEach(x=>x.onclick=()=>route("performance"))}
function route(n){document.body.innerHTML=shell(n==="detail"?"analysis":n);({dashboard,matches,analysis,signals,more,performance,detail}[n]||dashboard)();scrollTo(0,0)}
route("dashboard");if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js?v=1.1.0",{updateViaCache:"none"}).catch(()=>{}));
