const DEMO={
featured:{league:"Serie A",home:"Milan",away:"Roma",time:"18:00",hc:"MIL",ac:"ROM",hcl:"milan",acl:"roma",result:["1",74],goals:["GOL",68],ou:["OVER 2.5",61]},
games:[
["18:00","Milan","Roma","74%","MIL","ROM","milan","roma","Serie A"],
["18:30","Arsenal","Chelsea","61%","ARS","CHE","arsenal","chelsea","Premier League"],
["20:00","Barcelona","Sevilla","68%","BAR","SEV","barcelona","sevilla","La Liga"],
["20:30","Bayern","Leverkusen","55%","BAY","LEV","bayern","leverkusen","Bundesliga"],
["21:00","PSG","Lyon","72%","PSG","LYO","psg","lyon","Ligue 1"]
],
signals:[
["ALTA CONVERGENZA","1","Milan vs Roma","74%","FORTE","up"],
["VALUE / EDGE","GOL","Arsenal vs Chelsea","+12%","INTERESSANTE","value"],
["ALTA CONVERGENZA","OVER 2.5","Barcelona vs Sevilla","68%","BUONA","up"]
]};
const crest=(c,cl="")=>`<div class="crest ${cl}"><span>${c}</span></div>`;
const info=(t,x)=>`<button class="info" aria-label="Info ${t}" data-info="${encodeURIComponent(x)}">i</button>`;
function nav(id,icon,label,a){return `<button class="nav-item ${a===id?"active":""}" data-nav="${id}"><span class="nav-icon">${icon}</span><span>${label}</span></button>`}
function shell(a="dashboard"){return `<header class="topbar"><button class="icon-btn" id="menuBtn"><span></span><span></span><span></span></button><div class="brand"><div class="brand-name">SPACE16154</div><div class="brand-sub">FOOTBALL INTELLIGENCE</div></div><div class="engine"><i></i></div></header><main id="main"></main><nav class="bottom-nav">${nav("dashboard","⌂","Dashboard",a)}${nav("matches","□","Matches",a)}${nav("analysis","◇","Analisi",a)}${nav("teams","♙","Squadre",a)}${nav("more","•••","Altro",a)}</nav>`}
function stat(t,v,s,i,p,g){return `<button class="stat-card" data-nav="${g}"><div class="stat-top"><span>${t}</span><b>${i}</b></div><strong>${v}</strong><small>${s}</small><div class="progress"><i style="width:${p}%"></i></div></button>`}
function pred(a,b,c,d){return `<div class="pred-card"><small>${a}</small><span>${b}</span><strong>${c}</strong><em>${d}%</em></div>`}
function featured(){let f=DEMO.featured;return `<section class="panel"><div class="section-head"><h2>☆ &nbsp; MATCH IN EVIDENZA</h2><span>${f.league}</span></div><div class="match-hero"><div class="club">${crest(f.hc,f.hcl)}<strong>${f.home}</strong></div><div class="match-time"><b>${f.time}</b><span>OGGI</span><em>VS</em></div><div class="club">${crest(f.ac,f.acl)}<strong>${f.away}</strong></div></div><div class="prediction-grid">${pred("1X2","ESITO PIÙ PROBABILE",f.result[0],f.result[1])}${pred("GOL / NO GOL","ESITO PIÙ PROBABILE",f.goals[0],f.goals[1])}${pred("OVER / UNDER 2.5","ESITO PIÙ PROBABILE",f.ou[0],f.ou[1])}</div><button class="primary-btn" data-open-analysis>VAI ALL'ANALISI COMPLETA <span>›</span></button></section>`}
function upcoming(){return `<section class="panel"><div class="section-head"><h2>PROSSIME PARTITE</h2><button class="text-btn" data-nav="matches">VEDI TUTTE ›</button></div>${DEMO.games.slice(1).map(g=>`<button class="fixture" data-open-analysis><div><b>${g[0]}</b><small>OGGI</small></div><div class="fixture-team">${crest(g[4],g[6])}<span>${g[1]}</span></div><b class="vs">VS</b><div class="fixture-team away"><span>${g[2]}</span>${crest(g[5],g[7])}</div><span class="competition">${g[8]}</span><span class="chev">›</span></button>`).join("")}</section>`}
function signals(){return `<section class="panel"><div class="section-head"><h2>◎ &nbsp; TOP SIGNALS</h2><button class="text-btn" data-nav="matches">VEDI TUTTI ›</button></div><div class="signal-row">${DEMO.signals.map(s=>`<article class="signal ${s[5]}"><div class="signal-type">${s[0]} ${info(s[0],s[5]==="value"?"Value / Edge indica un potenziale scostamento tra quota implicita e stima del modello. Non è una probabilità aggiuntiva.":"Alta Convergenza indica che più famiglie di indicatori indipendenti puntano nella stessa direzione. È una misura di coerenza.")}</div><div class="signal-main">${s[1]}</div><div class="signal-match">${s[2]}</div><div class="signal-bottom"><span>${s[4]}</span><strong>${s[3]}</strong></div></article>`).join("")}</div></section>`}
function dashboard(){document.querySelector("#main").innerHTML=`<div class="page"><div class="page-title-row"><div><div class="eyebrow">PANORAMICA</div><h1>DASHBOARD</h1><p>Il quadro sintetico prima di entrare nel dettaglio.</p></div><button class="date-btn">5 AGOSTO 2026⌄</button></div><div class="stats">${stat("PARTITE OGGI","18","Vai alla lista completa","□",67,"matches")}${stat("SEGNALI","7","Opportunità rilevate","◎",52,"matches")}${stat("CONFIDENCE MEDIA","71%","Coerenza dei segnali","◉",71,"analysis")}${stat("DATA QUALITY","96%","Copertura dati","✓",96,"analysis")}</div>${featured()}${upcoming()}${signals()}</div>`;bind()}
function matches(){let leagues=["Serie A","Premier League","La Liga","Bundesliga","Ligue 1"];document.querySelector("#main").innerHTML=`<div class="page"><div class="eyebrow">CALENDARIO</div><h1>MATCHES</h1><p class="subtitle">Scegli una competizione e poi entra nell'analisi.</p><div class="league-stack">${leagues.map((l,i)=>`<button class="league-row ${i===0?"active":""}"><span>${l}</span><b>${i===0?3:2}</b><em>›</em></button>`).join("")}</div><section class="panel"><div class="section-head"><h2>PARTITE DEL GIORNO</h2><span>5 disponibili</span></div>${DEMO.games.map(g=>`<button class="match-list" data-open-analysis><span>${g[0]}</span><div>${crest(g[4],g[6])}<b>${g[1]}</b></div><em>VS</em><div><b>${g[2]}</b>${crest(g[5],g[7])}</div><strong>${g[3]}</strong><small>${g[8]}</small></button>`).join("")}</section></div>`;bind()}
function reason(l,a,b,t){let x=parseFloat(a),y=parseFloat(b),m=Math.max(x,y,1);return `<div class="reason"><div class="reason-label">${l}</div><div class="reason-values"><b>${a}</b><b>${b}</b></div><div class="reason-bars"><i style="width:${x/m*100}%"></i><i style="width:${y/m*100}%"></i></div><p>${t}</p></div>`}
function row(a,b,c,t){return `<div class="compare-row"><span>${a} ${info(a,t)}</span><b>${b}</b><b>${c}</b></div>`}
function mini(a,b,t){return `<div class="mini-card"><span>${a} ${info(a,t)}</span><b>${b}</b></div>`}
function analysis(){document.querySelector("#main").innerHTML=`<div class="page analysis-page"><div class="eyebrow">MATCH ANALYSIS</div><h1>Milan — Roma</h1><p class="subtitle">Serie A · pre-match · dati demo</p>
<section class="panel model-card"><div class="section-head"><h2>MODELLO ${info("Modello","Il modello combina probabilità di esito, qualità delle occasioni, rendimento recente, comportamento nell'ultimo terzo e fattore campo. Confidence misura la coerenza tra questi blocchi; Edge misura il potenziale valore rispetto alla quota, quando disponibile.")}</h2><div class="badges"><span class="badge green">ALTA CONVERGENZA</span><span class="badge gold">EDGE +15%</span></div></div>
<div class="model-probs"><div><small>1</small><b>74%</b><span>Milan</span></div><div><small>X</small><b>5%</b><span>Pareggio</span></div><div><small>2</small><b>21%</b><span>Roma</span></div></div>
<div class="confidence-box"><div><span>CONFIDENCE ${info("Confidence","Non è una seconda probabilità: misura quanto i principali blocchi analitici sono coerenti tra loro.")}</span><strong>75%</strong></div><div class="big-progress"><i style="width:75%"></i></div><p>Alta coerenza tra produzione offensiva, difesa, forma e controllo dell'ultimo terzo.</p></div>
<div class="model-explain"><div class="explain-title">PERCHÉ IL MODELLO VEDE MILAN?</div>${reason("xG","1.84","1.21","Produzione di occasioni attese superiore.")}${reason("xGA","0.94","1.37","Concede occasioni di qualità inferiore.")}${reason("FORMA","78%","61%","Indice delle ultime 5 gare, ponderato per recenza e qualità della performance.")}${reason("ULTIMO TERZO","64","47","Più presenza e pericolosità nelle zone avanzate.")}${reason("QUALITÀ TIRO","0.13","0.10","xG medio per tiro: evita di premiare semplicemente il volume.")}</div>
<div class="model-note"><b>LETTURA DEL SEGNALE</b><strong>Value / Edge +15%</strong><p>Il vantaggio nasce dalla combinazione dei fattori sopra. L'Edge non si somma alla probabilità: segnala un potenziale scostamento tra modello e quota.</p><div class="risk"><b>⚠ RISCHIO PRINCIPALE</b><span>Fattore campo e forma recente hanno un peso rilevante.</span></div></div></section>
<section class="panel methodology"><div class="section-head"><h2>COME VIENE CALCOLATA LA FORMA? ${info("Forma","Indice composito delle ultime 5 partite: non è una semplice media di vittorie e sconfitte.")}</h2><span>ULTIME 5</span></div><div class="method-grid"><div><b>35%</b><span>Risultato recente</span><small>Punti + differenza gol</small></div><div><b>25%</b><span>Qualità performance</span><small>xG − xGA</small></div><div><b>25%</b><span>Creazione</span><small>xG + xThreat</small></div><div><b>15%</b><span>Recenza</span><small>più peso alle gare recenti</small></div></div><p class="method-copy"><strong>+17% forma</strong> significa che l'indice composito del Milan è superiore a quello della Roma del 17% nel confronto normalizzato. Non significa 17% di probabilità in più.</p></section>
<section class="panel"><div class="section-head"><h2>CONFRONTO DATI</h2><span>Milan · Roma</span></div><div class="compare-head"><span>INDICATORE</span><b>MIL</b><b>ROM</b></div>${row("xG","1.84","1.21","Qualità e quantità delle occasioni create.")}${row("xGA","0.94","1.37","Qualità delle occasioni concesse.")}${row("xThreat ultimo terzo","1.42","0.96","Pericolosità territoriale generata nelle zone avanzate.")}${row("Entrate in area","18","11","Possessi che entrano nell'area avversaria.")}${row("Tiri in porta","6","4","Più informativo dei tiri totali, ma letto insieme a xG.")}${row("xG / tiro","0.13","0.10","Qualità media della conclusione.")}${row("Possesso","58%","42%","Contesto: peso ridotto rispetto alla pericolosità.")}</section>
<section class="panel"><div class="section-head"><h2>INDICATORI DI CONTROLLO</h2><span>NON DECIDONO DA SOLI</span></div><div class="advanced">${mini("Pressione alta","67 — 49","Volume e recuperi avanzati.")}${mini("Progressioni","54 — 39","Avanzamento efficace verso l'ultimo terzo.")}${mini("Corner","6 — 4","Segnale secondario di pressione.")}${mini("Clean sheet","42% — 31%","Solidità recente.")}</div></section>
<section class="panel reliability"><div class="section-head"><h2>DATI E AFFIDABILITÀ</h2><span class="quality">96%</span></div><div class="quality-list"><div><span>Fixture</span><b>Completo</b></div><div><span>xG / xGA</span><b>Completo</b></div><div><span>Forma ultime 5</span><b>Completo</b></div><div><span>Quote</span><b>Demo</b></div></div></section></div>`;bind()}
function simple(t,p){document.querySelector("#main").innerHTML=`<div class="page empty"><div class="eyebrow">SPACE16154</div><h1>${t}</h1><p>${p}</p><div class="panel demo-note"><b>V3 · STRUTTURA PRONTA</b><span>Questa sezione sarà collegata ai dati reali nel prossimo step.</span></div></div>`;bind()}
function showInfo(t){let o=document.createElement("div");o.className="modal-backdrop";o.innerHTML=`<div class="info-modal"><button class="modal-x">×</button><div class="eyebrow">INFO</div><p>${t}</p></div>`;document.body.appendChild(o);o.querySelector(".modal-x").onclick=()=>o.remove();o.onclick=e=>{if(e.target===o)o.remove()}}
function bind(){document.querySelectorAll("[data-nav]").forEach(b=>b.onclick=()=>route(b.dataset.nav));document.querySelectorAll("[data-open-analysis]").forEach(b=>b.onclick=()=>route("analysis"));document.querySelectorAll(".info").forEach(b=>b.onclick=e=>{e.stopPropagation();showInfo(decodeURIComponent(b.dataset.info))});let m=document.querySelector("#menuBtn");if(m)m.onclick=()=>showInfo("La navigazione principale resta nella barra inferiore. Il menu superiore viene tenuto per funzioni secondarie, evitando di duplicare Dashboard, Matches e Analisi.")}
function route(n){document.body.innerHTML=shell(n);if(n==="dashboard")dashboard();else if(n==="matches")matches();else if(n==="analysis")analysis();else if(n==="teams")simple("Squadre","Ranking, forma e profili squadra.");else simple("Altro","Impostazioni e funzioni future.");scrollTo(0,0)}
route("dashboard");
